name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install lastest stable rust
      uses: actions-rs/toolchain@v1
      with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
            
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf


    - name: install pnpm
      run: |
        npm install -g pnpm
    
    - name: install dependency
      run: |
        pnpm install
        
    - name: unit test
      run: |
        pnpm test
        
    - name: build
      run: |
        pnpm build
        
    - name: Package
      run: |
        pnpm tauri build
        
